FLAGS = [
    {"emoji": "🇺🇸", "country": "United States", "capital": "Washington, D.C."},
    {"emoji": "🇬🇧", "country": "United Kingdom", "capital": "London"},
    {"emoji": "🇩🇪", "country": "Germany", "capital": "Berlin"},
    {"emoji": "🇫🇷", "country": "France", "capital": "Paris"},
    {"emoji": "🇯🇵", "country": "Japan", "capital": "Tokyo"},
    {"emoji": "🇪🇸", "country": "Spain", "capital": "Madrid"},
    {"emoji": "🇮🇹", "country": "Italy", "capital": "Rome"},
    {"emoji": "🇨🇦", "country": "Canada", "capital": "Ottawa"},
    {"emoji": "🇧🇷", "country": "Brazil", "capital": "Brasília"},
    {"emoji": "🇲🇽", "country": "Mexico", "capital": "Mexico City"},
    {"emoji": "🇨🇳", "country": "China", "capital": "Beijing"},
    {"emoji": "🇰🇷", "country": "South Korea", "capital": "Seoul"},
    {"emoji": "🇦🇺", "country": "Australia", "capital": "Canberra"},
    {"emoji": "🇳🇬", "country": "Nigeria", "capital": "Abuja"},
    {"emoji": "🇮🇳", "country": "India", "capital": "New Delhi"},
    {"emoji": "🇷🇺", "country": "Russia", "capital": "Moscow"},
    {"emoji": "🇹🇷", "country": "Turkey", "capital": "Ankara"},
    {"emoji": "🇸🇦", "country": "Saudi Arabia", "capital": "Riyadh"},
    {"emoji": "🇿🇦", "country": "South Africa", "capital": "Pretoria"},
    {"emoji": "🇸🇪", "country": "Sweden", "capital": "Stockholm"},
    {"emoji": "🇳🇿", "country": "New Zealand", "capital": "Wellington"},
    {"emoji": "🇦🇷", "country": "Argentina", "capital": "Buenos Aires"},
]
