"""Flag emoji dataset.

This list was compiled using `pycountry` for country names and ISO codes,
the `emoji` package for flag emojis, and capital city data from the
[REST Countries API](https://restcountries.com/). To regenerate it:

1. Install dependencies:
   ```bash
   pip install pycountry emoji requests
   ```
2. Run a small script that fetches each country's capital and flag:
   ```python
   import json, requests, pycountry, emoji

   records = []
   for country in pycountry.countries:
       code = country.alpha_2
       flag = emoji.flag(code)
       resp = requests.get(f"https://restcountries.com/v3.1/alpha/{code}")
       capital = resp.json()[0].get("capital", [""])[0]
       records.append({"emoji": flag, "country": country.name, "capital": capital})

   print(json.dumps(records, ensure_ascii=False, indent=4))
   ```
3. Copy the printed JSON into `FLAGS` below.
"""

FLAGS = [
    {'emoji': '🇦🇫', 'country': 'Afghanistan', 'capital': 'Kabul'},
    {'emoji': '🇦🇱', 'country': 'Albania', 'capital': 'Tirana'},
    {'emoji': '🇩🇿', 'country': 'Algeria', 'capital': 'Algiers'},
    {'emoji': '🇦🇸', 'country': 'American Samoa', 'capital': 'Pago Pago'},
    {'emoji': '🇦🇩', 'country': 'Andorra', 'capital': 'Andorra la Vella'},
    {'emoji': '🇦🇴', 'country': 'Angola', 'capital': 'Luanda'},
    {'emoji': '🇦🇮', 'country': 'Anguilla', 'capital': 'The Valley'},
    {'emoji': '🇦🇶', 'country': 'Antarctica', 'capital': ''},
    {'emoji': '🇦🇬', 'country': 'Antigua and Barbuda', 'capital': 'Saint John\'s'},
    {'emoji': '🇦🇷', 'country': 'Argentina', 'capital': 'Buenos Aires'},
    {'emoji': '🇦🇲', 'country': 'Armenia', 'capital': 'Yerevan'},
    {'emoji': '🇦🇼', 'country': 'Aruba', 'capital': 'Oranjestad'},
    {'emoji': '🇦🇺', 'country': 'Australia', 'capital': 'Canberra'},
    {'emoji': '🇦🇹', 'country': 'Austria', 'capital': 'Vienna'},
    {'emoji': '🇦🇿', 'country': 'Azerbaijan', 'capital': 'Baku'},
    {'emoji': '🇧🇸', 'country': 'Bahamas', 'capital': 'Nassau'},
    {'emoji': '🇧🇭', 'country': 'Bahrain', 'capital': 'Manama'},
    {'emoji': '🇧🇩', 'country': 'Bangladesh', 'capital': 'Dhaka'},
    {'emoji': '🇧🇧', 'country': 'Barbados', 'capital': 'Bridgetown'},
    {'emoji': '🇧🇾', 'country': 'Belarus', 'capital': 'Minsk'},
    {'emoji': '🇧🇪', 'country': 'Belgium', 'capital': 'Brussels'},
    {'emoji': '🇧🇿', 'country': 'Belize', 'capital': 'Belmopan'},
    {'emoji': '🇧🇯', 'country': 'Benin', 'capital': 'Porto-Novo'},
    {'emoji': '🇧🇲', 'country': 'Bermuda', 'capital': 'Hamilton'},
    {'emoji': '🇧🇹', 'country': 'Bhutan', 'capital': 'Thimphu'},
    {'emoji': '🇧🇴', 'country': 'Bolivia', 'capital': 'Sucre'},
    {'emoji': '🇧🇦', 'country': 'Bosnia and Herzegovina', 'capital': 'Sarajevo'},
    {'emoji': '🇧🇼', 'country': 'Botswana', 'capital': 'Gaborone'},
    {'emoji': '🇧🇻', 'country': 'Bouvet Island', 'capital': ''},
    {'emoji': '🇧🇷', 'country': 'Brazil', 'capital': 'Brasília'},
    {'emoji': '🇮🇴', 'country': 'British Indian Ocean Territory', 'capital': 'Diego Garcia'},
    {'emoji': '🇻🇬', 'country': 'British Virgin Islands', 'capital': 'Road Town'},
    {'emoji': '🇧🇳', 'country': 'Brunei', 'capital': 'Bandar Seri Begawan'},
    {'emoji': '🇧🇬', 'country': 'Bulgaria', 'capital': 'Sofia'},
    {'emoji': '🇧🇫', 'country': 'Burkina Faso', 'capital': 'Ouagadougou'},
    {'emoji': '🇧🇮', 'country': 'Burundi', 'capital': 'Gitega'},
    {'emoji': '🇰🇭', 'country': 'Cambodia', 'capital': 'Phnom Penh'},
    {'emoji': '🇨🇲', 'country': 'Cameroon', 'capital': 'Yaoundé'},
    {'emoji': '🇨🇦', 'country': 'Canada', 'capital': 'Ottawa'},
    {'emoji': '🇨🇻', 'country': 'Cape Verde', 'capital': 'Praia'},
    {'emoji': '🇧🇶', 'country': 'Caribbean Netherlands', 'capital': 'Kralendijk'},
    {'emoji': '🇰🇾', 'country': 'Cayman Islands', 'capital': 'George Town'},
    {'emoji': '🇨🇫', 'country': 'Central African Republic', 'capital': 'Bangui'},
    {'emoji': '🇹🇩', 'country': 'Chad', 'capital': 'N\'Djamena'},
    {'emoji': '🇨🇱', 'country': 'Chile', 'capital': 'Santiago'},
    {'emoji': '🇨🇳', 'country': 'China', 'capital': 'Beijing'},
    {'emoji': '🇨🇽', 'country': 'Christmas Island', 'capital': 'Flying Fish Cove'},
    {'emoji': '🇨🇨', 'country': 'Cocos (Keeling) Islands', 'capital': 'West Island'},
    {'emoji': '🇨🇴', 'country': 'Colombia', 'capital': 'Bogotá'},
    {'emoji': '🇰🇲', 'country': 'Comoros', 'capital': 'Moroni'},
    {'emoji': '🇨🇰', 'country': 'Cook Islands', 'capital': 'Avarua'},
    {'emoji': '🇨🇷', 'country': 'Costa Rica', 'capital': 'San José'},
    {'emoji': '🇭🇷', 'country': 'Croatia', 'capital': 'Zagreb'},
    {'emoji': '🇨🇺', 'country': 'Cuba', 'capital': 'Havana'},
    {'emoji': '🇨🇼', 'country': 'Curaçao', 'capital': 'Willemstad'},
    {'emoji': '🇨🇾', 'country': 'Cyprus', 'capital': 'Nicosia'},
    {'emoji': '🇨🇿', 'country': 'Czechia', 'capital': 'Prague'},
    {'emoji': '🇨🇩', 'country': 'DR Congo', 'capital': 'Kinshasa'},
    {'emoji': '🇩🇰', 'country': 'Denmark', 'capital': 'Copenhagen'},
    {'emoji': '🇩🇯', 'country': 'Djibouti', 'capital': 'Djibouti'},
    {'emoji': '🇩🇲', 'country': 'Dominica', 'capital': 'Roseau'},
    {'emoji': '🇩🇴', 'country': 'Dominican Republic', 'capital': 'Santo Domingo'},
    {'emoji': '🇪🇨', 'country': 'Ecuador', 'capital': 'Quito'},
    {'emoji': '🇪🇬', 'country': 'Egypt', 'capital': 'Cairo'},
    {'emoji': '🇸🇻', 'country': 'El Salvador', 'capital': 'San Salvador'},
    {'emoji': '🇬🇶', 'country': 'Equatorial Guinea', 'capital': 'Malabo'},
    {'emoji': '🇪🇷', 'country': 'Eritrea', 'capital': 'Asmara'},
    {'emoji': '🇪🇪', 'country': 'Estonia', 'capital': 'Tallinn'},
    {'emoji': '🇸🇿', 'country': 'Eswatini', 'capital': 'Mbabane'},
    {'emoji': '🇪🇹', 'country': 'Ethiopia', 'capital': 'Addis Ababa'},
    {'emoji': '🇫🇰', 'country': 'Falkland Islands', 'capital': 'Stanley'},
    {'emoji': '🇫🇴', 'country': 'Faroe Islands', 'capital': 'Tórshavn'},
    {'emoji': '🇫🇯', 'country': 'Fiji', 'capital': 'Suva'},
    {'emoji': '🇫🇮', 'country': 'Finland', 'capital': 'Helsinki'},
    {'emoji': '🇫🇷', 'country': 'France', 'capital': 'Paris'},
    {'emoji': '🇬🇫', 'country': 'French Guiana', 'capital': 'Cayenne'},
    {'emoji': '🇵🇫', 'country': 'French Polynesia', 'capital': 'Papeetē'},
    {'emoji': '🇹🇫', 'country': 'French Southern and Antarctic Lands', 'capital': 'Port-aux-Français'},
    {'emoji': '🇬🇦', 'country': 'Gabon', 'capital': 'Libreville'},
    {'emoji': '🇬🇲', 'country': 'Gambia', 'capital': 'Banjul'},
    {'emoji': '🇬🇪', 'country': 'Georgia', 'capital': 'Tbilisi'},
    {'emoji': '🇩🇪', 'country': 'Germany', 'capital': 'Berlin'},
    {'emoji': '🇬🇭', 'country': 'Ghana', 'capital': 'Accra'},
    {'emoji': '🇬🇮', 'country': 'Gibraltar', 'capital': 'Gibraltar'},
    {'emoji': '🇬🇷', 'country': 'Greece', 'capital': 'Athens'},
    {'emoji': '🇬🇱', 'country': 'Greenland', 'capital': 'Nuuk'},
    {'emoji': '🇬🇩', 'country': 'Grenada', 'capital': 'St. George\'s'},
    {'emoji': '🇬🇵', 'country': 'Guadeloupe', 'capital': 'Basse-Terre'},
    {'emoji': '🇬🇺', 'country': 'Guam', 'capital': 'Hagåtña'},
    {'emoji': '🇬🇹', 'country': 'Guatemala', 'capital': 'Guatemala City'},
    {'emoji': '🇬🇬', 'country': 'Guernsey', 'capital': 'St. Peter Port'},
    {'emoji': '🇬🇳', 'country': 'Guinea', 'capital': 'Conakry'},
    {'emoji': '🇬🇼', 'country': 'Guinea-Bissau', 'capital': 'Bissau'},
    {'emoji': '🇬🇾', 'country': 'Guyana', 'capital': 'Georgetown'},
    {'emoji': '🇭🇹', 'country': 'Haiti', 'capital': 'Port-au-Prince'},
    {'emoji': '🇭🇲', 'country': 'Heard Island and McDonald Islands', 'capital': ''},
    {'emoji': '🇭🇳', 'country': 'Honduras', 'capital': 'Tegucigalpa'},
    {'emoji': '🇭🇰', 'country': 'Hong Kong', 'capital': 'City of Victoria'},
    {'emoji': '🇭🇺', 'country': 'Hungary', 'capital': 'Budapest'},
    {'emoji': '🇮🇸', 'country': 'Iceland', 'capital': 'Reykjavik'},
    {'emoji': '🇮🇳', 'country': 'India', 'capital': 'New Delhi'},
    {'emoji': '🇮🇩', 'country': 'Indonesia', 'capital': 'Jakarta'},
    {'emoji': '🇮🇷', 'country': 'Iran', 'capital': 'Tehran'},
    {'emoji': '🇮🇶', 'country': 'Iraq', 'capital': 'Baghdad'},
    {'emoji': '🇮🇪', 'country': 'Ireland', 'capital': 'Dublin'},
    {'emoji': '🇮🇲', 'country': 'Isle of Man', 'capital': 'Douglas'},
    {'emoji': '🇮🇱', 'country': 'Israel', 'capital': 'Jerusalem'},
    {'emoji': '🇮🇹', 'country': 'Italy', 'capital': 'Rome'},
    {'emoji': '🇨🇮', 'country': 'Ivory Coast', 'capital': 'Yamoussoukro'},
    {'emoji': '🇯🇲', 'country': 'Jamaica', 'capital': 'Kingston'},
    {'emoji': '🇯🇵', 'country': 'Japan', 'capital': 'Tokyo'},
    {'emoji': '🇯🇪', 'country': 'Jersey', 'capital': 'Saint Helier'},
    {'emoji': '🇯🇴', 'country': 'Jordan', 'capital': 'Amman'},
    {'emoji': '🇰🇿', 'country': 'Kazakhstan', 'capital': 'Astana'},
    {'emoji': '🇰🇪', 'country': 'Kenya', 'capital': 'Nairobi'},
    {'emoji': '🇰🇮', 'country': 'Kiribati', 'capital': 'South Tarawa'},
    {'emoji': '🇽🇰', 'country': 'Kosovo', 'capital': 'Pristina'},
    {'emoji': '🇰🇼', 'country': 'Kuwait', 'capital': 'Kuwait City'},
    {'emoji': '🇰🇬', 'country': 'Kyrgyzstan', 'capital': 'Bishkek'},
    {'emoji': '🇱🇦', 'country': 'Laos', 'capital': 'Vientiane'},
    {'emoji': '🇱🇻', 'country': 'Latvia', 'capital': 'Riga'},
    {'emoji': '🇱🇧', 'country': 'Lebanon', 'capital': 'Beirut'},
    {'emoji': '🇱🇸', 'country': 'Lesotho', 'capital': 'Maseru'},
    {'emoji': '🇱🇷', 'country': 'Liberia', 'capital': 'Monrovia'},
    {'emoji': '🇱🇾', 'country': 'Libya', 'capital': 'Tripoli'},
    {'emoji': '🇱🇮', 'country': 'Liechtenstein', 'capital': 'Vaduz'},
    {'emoji': '🇱🇹', 'country': 'Lithuania', 'capital': 'Vilnius'},
    {'emoji': '🇱🇺', 'country': 'Luxembourg', 'capital': 'Luxembourg'},
    {'emoji': '🇲🇴', 'country': 'Macau', 'capital': ''},
    {'emoji': '🇲🇬', 'country': 'Madagascar', 'capital': 'Antananarivo'},
    {'emoji': '🇲🇼', 'country': 'Malawi', 'capital': 'Lilongwe'},
    {'emoji': '🇲🇾', 'country': 'Malaysia', 'capital': 'Kuala Lumpur'},
    {'emoji': '🇲🇻', 'country': 'Maldives', 'capital': 'Malé'},
    {'emoji': '🇲🇱', 'country': 'Mali', 'capital': 'Bamako'},
    {'emoji': '🇲🇹', 'country': 'Malta', 'capital': 'Valletta'},
    {'emoji': '🇲🇭', 'country': 'Marshall Islands', 'capital': 'Majuro'},
    {'emoji': '🇲🇶', 'country': 'Martinique', 'capital': 'Fort-de-France'},
    {'emoji': '🇲🇷', 'country': 'Mauritania', 'capital': 'Nouakchott'},
    {'emoji': '🇲🇺', 'country': 'Mauritius', 'capital': 'Port Louis'},
    {'emoji': '🇾🇹', 'country': 'Mayotte', 'capital': 'Mamoudzou'},
    {'emoji': '🇲🇽', 'country': 'Mexico', 'capital': 'Mexico City'},
    {'emoji': '🇫🇲', 'country': 'Micronesia', 'capital': 'Palikir'},
    {'emoji': '🇲🇩', 'country': 'Moldova', 'capital': 'Chișinău'},
    {'emoji': '🇲🇨', 'country': 'Monaco', 'capital': 'Monaco'},
    {'emoji': '🇲🇳', 'country': 'Mongolia', 'capital': 'Ulan Bator'},
    {'emoji': '🇲🇪', 'country': 'Montenegro', 'capital': 'Podgorica'},
    {'emoji': '🇲🇸', 'country': 'Montserrat', 'capital': 'Plymouth'},
    {'emoji': '🇲🇦', 'country': 'Morocco', 'capital': 'Rabat'},
    {'emoji': '🇲🇿', 'country': 'Mozambique', 'capital': 'Maputo'},
    {'emoji': '🇲🇲', 'country': 'Myanmar', 'capital': 'Naypyidaw'},
    {'emoji': '🇳🇦', 'country': 'Namibia', 'capital': 'Windhoek'},
    {'emoji': '🇳🇷', 'country': 'Nauru', 'capital': 'Yaren'},
    {'emoji': '🇳🇵', 'country': 'Nepal', 'capital': 'Kathmandu'},
    {'emoji': '🇳🇱', 'country': 'Netherlands', 'capital': 'Amsterdam'},
    {'emoji': '🇳🇨', 'country': 'New Caledonia', 'capital': 'Nouméa'},
    {'emoji': '🇳🇿', 'country': 'New Zealand', 'capital': 'Wellington'},
    {'emoji': '🇳🇮', 'country': 'Nicaragua', 'capital': 'Managua'},
    {'emoji': '🇳🇪', 'country': 'Niger', 'capital': 'Niamey'},
    {'emoji': '🇳🇬', 'country': 'Nigeria', 'capital': 'Abuja'},
    {'emoji': '🇳🇺', 'country': 'Niue', 'capital': 'Alofi'},
    {'emoji': '🇳🇫', 'country': 'Norfolk Island', 'capital': 'Kingston'},
    {'emoji': '🇰🇵', 'country': 'North Korea', 'capital': 'Pyongyang'},
    {'emoji': '🇲🇰', 'country': 'North Macedonia', 'capital': 'Skopje'},
    {'emoji': '🇲🇵', 'country': 'Northern Mariana Islands', 'capital': 'Saipan'},
    {'emoji': '🇳🇴', 'country': 'Norway', 'capital': 'Oslo'},
    {'emoji': '🇴🇲', 'country': 'Oman', 'capital': 'Muscat'},
    {'emoji': '🇵🇰', 'country': 'Pakistan', 'capital': 'Islamabad'},
    {'emoji': '🇵🇼', 'country': 'Palau', 'capital': 'Ngerulmud'},
    {'emoji': '🇵🇸', 'country': 'Palestine', 'capital': 'Ramallah'},
    {'emoji': '🇵🇦', 'country': 'Panama', 'capital': 'Panama City'},
    {'emoji': '🇵🇬', 'country': 'Papua New Guinea', 'capital': 'Port Moresby'},
    {'emoji': '🇵🇾', 'country': 'Paraguay', 'capital': 'Asunción'},
    {'emoji': '🇵🇪', 'country': 'Peru', 'capital': 'Lima'},
    {'emoji': '🇵🇭', 'country': 'Philippines', 'capital': 'Manila'},
    {'emoji': '🇵🇳', 'country': 'Pitcairn Islands', 'capital': 'Adamstown'},
    {'emoji': '🇵🇱', 'country': 'Poland', 'capital': 'Warsaw'},
    {'emoji': '🇵🇹', 'country': 'Portugal', 'capital': 'Lisbon'},
    {'emoji': '🇵🇷', 'country': 'Puerto Rico', 'capital': 'San Juan'},
    {'emoji': '🇶🇦', 'country': 'Qatar', 'capital': 'Doha'},
    {'emoji': '🇨🇬', 'country': 'Republic of the Congo', 'capital': 'Brazzaville'},
    {'emoji': '🇷🇴', 'country': 'Romania', 'capital': 'Bucharest'},
    {'emoji': '🇷🇺', 'country': 'Russia', 'capital': 'Moscow'},
    {'emoji': '🇷🇼', 'country': 'Rwanda', 'capital': 'Kigali'},
    {'emoji': '🇷🇪', 'country': 'Réunion', 'capital': 'Saint-Denis'},
    {'emoji': '🇧🇱', 'country': 'Saint Barthélemy', 'capital': 'Gustavia'},
    {'emoji': '🇸🇭', 'country': 'Saint Helena, Ascension and Tristan da Cunha', 'capital': 'Jamestown'},
    {'emoji': '🇰🇳', 'country': 'Saint Kitts and Nevis', 'capital': 'Basseterre'},
    {'emoji': '🇱🇨', 'country': 'Saint Lucia', 'capital': 'Castries'},
    {'emoji': '🇲🇫', 'country': 'Saint Martin', 'capital': 'Marigot'},
    {'emoji': '🇵🇲', 'country': 'Saint Pierre and Miquelon', 'capital': 'Saint-Pierre'},
    {'emoji': '🇻🇨', 'country': 'Saint Vincent and the Grenadines', 'capital': 'Kingstown'},
    {'emoji': '🇼🇸', 'country': 'Samoa', 'capital': 'Apia'},
    {'emoji': '🇸🇲', 'country': 'San Marino', 'capital': 'City of San Marino'},
    {'emoji': '🇸🇦', 'country': 'Saudi Arabia', 'capital': 'Riyadh'},
    {'emoji': '🇸🇳', 'country': 'Senegal', 'capital': 'Dakar'},
    {'emoji': '🇷🇸', 'country': 'Serbia', 'capital': 'Belgrade'},
    {'emoji': '🇸🇨', 'country': 'Seychelles', 'capital': 'Victoria'},
    {'emoji': '🇸🇱', 'country': 'Sierra Leone', 'capital': 'Freetown'},
    {'emoji': '🇸🇬', 'country': 'Singapore', 'capital': 'Singapore'},
    {'emoji': '🇸🇽', 'country': 'Sint Maarten', 'capital': 'Philipsburg'},
    {'emoji': '🇸🇰', 'country': 'Slovakia', 'capital': 'Bratislava'},
    {'emoji': '🇸🇮', 'country': 'Slovenia', 'capital': 'Ljubljana'},
    {'emoji': '🇸🇧', 'country': 'Solomon Islands', 'capital': 'Honiara'},
    {'emoji': '🇸🇴', 'country': 'Somalia', 'capital': 'Mogadishu'},
    {'emoji': '🇿🇦', 'country': 'South Africa', 'capital': 'Pretoria'},
    {'emoji': '🇬🇸', 'country': 'South Georgia', 'capital': 'King Edward Point'},
    {'emoji': '🇰🇷', 'country': 'South Korea', 'capital': 'Seoul'},
    {'emoji': '🇸🇸', 'country': 'South Sudan', 'capital': 'Juba'},
    {'emoji': '🇪🇸', 'country': 'Spain', 'capital': 'Madrid'},
    {'emoji': '🇱🇰', 'country': 'Sri Lanka', 'capital': 'Sri Jayawardenepura Kotte'},
    {'emoji': '🇸🇩', 'country': 'Sudan', 'capital': 'Khartoum'},
    {'emoji': '🇸🇷', 'country': 'Suriname', 'capital': 'Paramaribo'},
    {'emoji': '🇸🇯', 'country': 'Svalbard and Jan Mayen', 'capital': 'Longyearbyen'},
    {'emoji': '🇸🇪', 'country': 'Sweden', 'capital': 'Stockholm'},
    {'emoji': '🇨🇭', 'country': 'Switzerland', 'capital': 'Bern'},
    {'emoji': '🇸🇾', 'country': 'Syria', 'capital': 'Damascus'},
    {'emoji': '🇸🇹', 'country': 'São Tomé and Príncipe', 'capital': 'São Tomé'},
    {'emoji': '🇹🇼', 'country': 'Taiwan', 'capital': 'Taipei'},
    {'emoji': '🇹🇯', 'country': 'Tajikistan', 'capital': 'Dushanbe'},
    {'emoji': '🇹🇿', 'country': 'Tanzania', 'capital': 'Dodoma'},
    {'emoji': '🇹🇭', 'country': 'Thailand', 'capital': 'Bangkok'},
    {'emoji': '🇹🇱', 'country': 'Timor-Leste', 'capital': 'Dili'},
    {'emoji': '🇹🇬', 'country': 'Togo', 'capital': 'Lomé'},
    {'emoji': '🇹🇰', 'country': 'Tokelau', 'capital': 'Fakaofo'},
    {'emoji': '🇹🇴', 'country': 'Tonga', 'capital': 'Nuku\'alofa'},
    {'emoji': '🇹🇹', 'country': 'Trinidad and Tobago', 'capital': 'Port of Spain'},
    {'emoji': '🇹🇳', 'country': 'Tunisia', 'capital': 'Tunis'},
    {'emoji': '🇹🇷', 'country': 'Turkey', 'capital': 'Ankara'},
    {'emoji': '🇹🇲', 'country': 'Turkmenistan', 'capital': 'Ashgabat'},
    {'emoji': '🇹🇨', 'country': 'Turks and Caicos Islands', 'capital': 'Cockburn Town'},
    {'emoji': '🇹🇻', 'country': 'Tuvalu', 'capital': 'Funafuti'},
    {'emoji': '🇺🇬', 'country': 'Uganda', 'capital': 'Kampala'},
    {'emoji': '🇺🇦', 'country': 'Ukraine', 'capital': 'Kyiv'},
    {'emoji': '🇦🇪', 'country': 'United Arab Emirates', 'capital': 'Abu Dhabi'},
    {'emoji': '🇬🇧', 'country': 'United Kingdom', 'capital': 'London'},
    {'emoji': '🇺🇸', 'country': 'United States', 'capital': 'Washington, D.C.'},
    {'emoji': '🇺🇲', 'country': 'United States Minor Outlying Islands', 'capital': 'Washington DC'},
    {'emoji': '🇻🇮', 'country': 'United States Virgin Islands', 'capital': 'Charlotte Amalie'},
    {'emoji': '🇺🇾', 'country': 'Uruguay', 'capital': 'Montevideo'},
    {'emoji': '🇺🇿', 'country': 'Uzbekistan', 'capital': 'Tashkent'},
    {'emoji': '🇻🇺', 'country': 'Vanuatu', 'capital': 'Port Vila'},
    {'emoji': '🇻🇦', 'country': 'Vatican City', 'capital': 'Vatican City'},
    {'emoji': '🇻🇪', 'country': 'Venezuela', 'capital': 'Caracas'},
    {'emoji': '🇻🇳', 'country': 'Vietnam', 'capital': 'Hanoi'},
    {'emoji': '🇼🇫', 'country': 'Wallis and Futuna', 'capital': 'Mata-Utu'},
    {'emoji': '🇪🇭', 'country': 'Western Sahara', 'capital': 'El Aaiún'},
    {'emoji': '🇾🇪', 'country': 'Yemen', 'capital': 'Sana\'a'},
    {'emoji': '🇿🇲', 'country': 'Zambia', 'capital': 'Lusaka'},
    {'emoji': '🇿🇼', 'country': 'Zimbabwe', 'capital': 'Harare'},
    {'emoji': '🇦🇽', 'country': 'Åland Islands', 'capital': 'Mariehamn'},
]
